// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1280626051fdb272 "MyWebAppOMK", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Open' // Variant
 * headerText?: string // Header Text
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-4KAJ7G65.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-RUB5WN3S.js";
import { stdin_default } from "./chunks/chunk-X5RRBHLG.js";
import { className, css, fonts } from "./chunks/chunk-V7X3YXJE.js";
import "./chunks/chunk-EMY4GVBR.js";
import { routes } from "./chunks/chunk-4RKJF2MS.js";

// virtual:header-navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dlVypF9clhVKD0qX7G3X/3AKor5R9nlUGgg167wPH/OklZmszVl.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	CycleVariantState,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var NavigationMenuFonts = getFonts(stdin_default2);
var NavigationButtonFonts = getFonts(stdin_default);
var cycleOrder = ["ZTON6xOas", "qL7ycxAlq"];
var serializationHash = "framer-RTx0Q";
var variantClassNames = {
	qL7ycxAlq: "framer-v-13nc37y",
	ZTON6xOas: "framer-v-1db5fl4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "ZTON6xOas",
	Open: "qL7ycxAlq",
};
var getProps = ({ headerText, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ZTON6xOas",
		vulxb9JdP: headerText ?? props.vulxb9JdP ?? "Oliver King's Resume",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		vulxb9JdP: vulxb9JdP2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZTON6xOas",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const kl2_suW7Xfthvs6 = activeVariantCallback(async (...args) => {
		setVariant("ZTON6xOas");
	});
	const u3EQpGoKNgnqhaj = activeVariantCallback(async (...args) => {
		setVariant(CycleVariantState);
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "qL7ycxAlq") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.header
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1db5fl4",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ZTON6xOas"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-ac9cb30b-a01e-4275-be89-8cf1cbb70095, rgb(43, 43, 43))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-92d8255a-feac-4aed-ab72-dbce294d5959, rgb(16, 16, 17))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								qL7ycxAlq: {
									"data-framer-name": "Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1f29uqh"}
							data-framer-name={"Inner Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"jrFQGxlay"}
						>
							{isDisplayed() && (
								<ComponentViewportProvider
									{...addPropertyOverrides(
										{
											qL7ycxAlq: {
												height: 259,
												width: `min(${componentViewport?.width || "100vw"} - 32px, 712px)`,
												y:
													(componentViewport?.y || 0) +
													8 +
													(((componentViewport?.height || 353) - 16 - 337) / 2 +
														0 +
														0) +
													16 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1cwn4zh-container"}
										layoutDependency={layoutDependency}
										layoutId={"ZQmHxu6ks-container"}
										nodeId={"ZQmHxu6ks"}
										rendersWithMotion={true}
										scopeId={"OklZmszVl"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "ZQmHxu6ks",
											kl2_suW7X: kl2_suW7Xfthvs6,
											layoutId: "ZQmHxu6ks",
											style: {
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							<motion.div
								className={"framer-1sayho2"}
								data-framer-name={"Bar Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"OP4JB_xZP"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1dgpvch"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"xg24ehwbB"}
									text={vulxb9JdP2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1hy0j4h"}
											data-styles-preset={"uSha1VCB0"}
										>
											<Link
												href={{
													hash: ":l134k9EST",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"xg24ehwbB"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"OklZmszVl"}
												smoothScroll={true}
											>
												<motion.a
													className={"framer-styles-preset-1a67nrz"}
													data-styles-preset={"dSqx8LKPg"}
												>
													{"Jake Smith's Resume"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<ComponentViewportProvider
									height={30}
									y={
										(componentViewport?.y || 0) +
										8 +
										(((componentViewport?.height || 46.5) - 16 - 30) / 2 +
											0 +
											0) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											qL7ycxAlq: {
												y:
													(componentViewport?.y || 0) +
													8 +
													(((componentViewport?.height || 353) - 16 - 337) / 2 +
														0 +
														0) +
													16 +
													291 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-16uw6ux-container"}
										layoutDependency={layoutDependency}
										layoutId={"jGlJP8Ld0-container"}
										nodeId={"jGlJP8Ld0"}
										rendersWithMotion={true}
										scopeId={"OklZmszVl"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "jGlJP8Ld0",
											layoutId: "jGlJP8Ld0",
											u3EQpGoKN: u3EQpGoKNgnqhaj,
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.header>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RTx0Q.framer-1q7kiqp, .framer-RTx0Q .framer-1q7kiqp { display: block; }",
	".framer-RTx0Q.framer-1db5fl4 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 8px 16px 8px 16px; position: relative; width: 1200px; }",
	".framer-RTx0Q .framer-1f29uqh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; max-width: 712px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RTx0Q .framer-1cwn4zh-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-RTx0Q .framer-1sayho2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RTx0Q .framer-1dgpvch { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-RTx0Q .framer-16uw6ux-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-RTx0Q.framer-v-13nc37y .framer-1f29uqh { padding: 16px 0px 0px 0px; }",
	...css,
	...css2,
	'.framer-RTx0Q[data-border="true"]::after, .framer-RTx0Q [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerOklZmszVl = withCSS(Component, css3, "framer-RTx0Q");
var stdin_default3 = FramerOklZmszVl;
FramerOklZmszVl.displayName = "Header Navigation";
FramerOklZmszVl.defaultProps = {
	height: 46.5,
	width: 1200,
};
addPropertyControls(FramerOklZmszVl, {
	variant: {
		options: ["ZTON6xOas", "qL7ycxAlq"],
		optionTitles: ["Desktop", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vulxb9JdP: {
		defaultValue: "Oliver King's Resume",
		displayTextArea: false,
		title: "Header Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerOklZmszVl,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavigationMenuFonts,
		...NavigationButtonFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header-navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderNavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var header_navigation_default = ComponentWithRoot;
export { header_navigation_default as default };
