// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1280626051fdb272 "MyWebAppOMK", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * jobTitle?: string // Job Title
 * timeframe?: string // Timeframe
 * company?: string // Company
 * location?: string // Location
 * jobDescription?: string // Job Description
 * current?: boolean // Current
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-KAGOU6RE.js";
import {
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default4,
} from "./chunks/chunk-RWVAQEMV.js";
import { stdin_default } from "./chunks/chunk-XBQFWPRW.js";
import "./chunks/chunk-TYUG5XBE.js";
import { className, css, fonts } from "./chunks/chunk-6HGRWQMP.js";
import "./chunks/chunk-V7X3YXJE.js";
import "./chunks/chunk-EMY4GVBR.js";
import { routes } from "./chunks/chunk-4RKJF2MS.js";

// virtual:job-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/X2CkIa5s28ay5MDjpY08/60w7VhViT6JtwTdKljXD/WUYpOtsm9.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/iFqcRxF8ZZEGF7diwteW/imM74r1wvRz3ZLLPqMiF/fYS5GjO1m.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 9 2.408 C 5.84 2.413 2.735 1.583 0 0.001 L 0 0.001 L 0 7.658 C 0 8.073 0.336 8.408 0.75 8.408 L 17.25 8.408 C 17.664 8.408 18 8.073 18 7.658 L 18 0 C 15.265 1.583 12.16 2.413 9 2.408 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="8.408437499999991px" id="yZxSY5tM2" transform="translate(3 11.092)" width="18px"/><path d="M 0 0 L 3 0" fill="transparent" height="1px" id="ZO1T9W9Kn" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(10.5 10.5)" width="3px"/><path d="M 0.75 13.5 C 0.336 13.5 0 13.164 0 12.75 L 0 0.75 C 0 0.336 0.336 0 0.75 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 L 18 12.75 C 18 13.164 17.664 13.5 17.25 13.5 Z" fill="transparent" height="13.5px" id="U1X8jGTeU" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 6)" width="18px"/><path d="M 7.5 3 L 7.5 1.5 C 7.5 0.672 6.828 0 6 0 L 1.5 0 C 0.672 0 0 0.672 0 1.5 L 0 3" fill="transparent" height="3px" id="NHVMwj9J3" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 3)" width="7.5px"/><path d="M 18 0 C 15.265 1.583 12.16 2.413 9 2.408 C 5.84 2.413 2.735 1.583 0 0.001" fill="transparent" height="2.408460292330787px" id="gCBdRGdgX" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 11.092)" width="18px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("405654161", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-ddSE1", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css2 = [
	`.framer-ddSE1 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-ddSE1");
Icon.displayName = "Briefcase";
var stdin_default5 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/X2CkIa5s28ay5MDjpY08/60w7VhViT6JtwTdKljXD/WUYpOtsm9.js
var HeadingFonts = getFonts(stdin_default);
var SmallInfoIconFonts = getFonts(stdin_default4);
var serializationHash = "framer-zU7Ek";
var variantClassNames = {
	d1f09tG2a: "framer-v-1i6sbp9",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({
	company,
	current,
	height,
	id,
	jobDescription,
	jobTitle,
	location,
	timeframe,
	width,
	...props
}) => {
	return {
		...props,
		DRAi1KyCB: current ?? props.DRAi1KyCB ?? true,
		ED1lsKYfZ: jobTitle ?? props.ED1lsKYfZ ?? "Full-Stack Developer",
		eYydo1Kt8: timeframe ?? props.eYydo1Kt8 ?? "2022 - Now",
		L4jz4no0O: company ?? props.L4jz4no0O ?? "Lumina Tech",
		vcBwwvsTj: location ?? props.vcBwwvsTj ?? "Berlin",
		y47aed1rw:
			jobDescription ??
			props.y47aed1rw ??
			"At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering. At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ED1lsKYfZ,
		eYydo1Kt8,
		L4jz4no0O,
		vcBwwvsTj,
		y47aed1rw,
		DRAi1KyCB,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "d1f09tG2a",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1i6sbp9",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"d1f09tG2a"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-ac9cb30b-a01e-4275-be89-8cf1cbb70095, rgb(43, 43, 43))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
					>
						<motion2.div
							className={"framer-1ixdmc0"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"igXHVPFwc"}
						>
							<ComponentViewportProvider height={22} width={"712px"}>
								<SmartComponentScopedContainer
									className={"framer-11t0jqo-container"}
									layoutDependency={layoutDependency}
									layoutId={"hjwsER5HR-container"}
									nodeId={"hjwsER5HR"}
									rendersWithMotion={true}
									scopeId={"WUYpOtsm9"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "hjwsER5HR",
										Kp3lxxlgQ: "Current",
										layoutId: "hjwsER5HR",
										ni42o9E7c: DRAi1KyCB,
										style: {
											width: "100%",
										},
										UCJ_lnTSR: ED1lsKYfZ,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion2.div
								className={"framer-o2razv"}
								data-framer-name={"Info Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"ndcJqg2uo"}
							>
								<ComponentViewportProvider height={16}>
									<SmartComponentScopedContainer
										className={"framer-1yggvvu-container"}
										layoutDependency={layoutDependency}
										layoutId={"HM9N5Ccba-container"}
										nodeId={"HM9N5Ccba"}
										rendersWithMotion={true}
										scopeId={"WUYpOtsm9"}
									>
										{_jsx2(stdin_default4, {
											bddaZ2nq1: stdin_default2,
											height: "100%",
											id: "HM9N5Ccba",
											layoutId: "HM9N5Ccba",
											MUWksGdyO: eYydo1Kt8,
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider height={16}>
									<SmartComponentScopedContainer
										className={"framer-wr1uck-container"}
										layoutDependency={layoutDependency}
										layoutId={"Q7KJ1jkOv-container"}
										nodeId={"Q7KJ1jkOv"}
										rendersWithMotion={true}
										scopeId={"WUYpOtsm9"}
									>
										{_jsx2(stdin_default4, {
											bddaZ2nq1: stdin_default5,
											height: "100%",
											id: "Q7KJ1jkOv",
											layoutId: "Q7KJ1jkOv",
											MUWksGdyO: L4jz4no0O,
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider height={16}>
									<SmartComponentScopedContainer
										className={"framer-1d7wac7-container"}
										layoutDependency={layoutDependency}
										layoutId={"DgoeTRQ09-container"}
										nodeId={"DgoeTRQ09"}
										rendersWithMotion={true}
										scopeId={"WUYpOtsm9"}
									>
										{_jsx2(stdin_default4, {
											bddaZ2nq1: stdin_default3,
											height: "100%",
											id: "DgoeTRQ09",
											layoutId: "DgoeTRQ09",
											MUWksGdyO: vcBwwvsTj,
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-11sf07u"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ff89uJIa3"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-e2b3e115-6772-4873-ba11-049b11b30d8f, rgb(164, 164, 164))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={y47aed1rw}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-3yhvoo"}
									data-styles-preset={"D9fLq48kA"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-e2b3e115-6772-4873-ba11-049b11b30d8f, rgb(164, 164, 164)))",
									}}
								>
									{
										"At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering. At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering."
									}
								</motion2.p>
							</React2.Fragment>
						</RichText>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zU7Ek.framer-1p44v12, .framer-zU7Ek .framer-1p44v12 { display: block; }",
	".framer-zU7Ek.framer-1i6sbp9 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 16px 0px; position: relative; width: 712px; }",
	".framer-zU7Ek .framer-1ixdmc0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-zU7Ek .framer-11t0jqo-container { flex: none; height: auto; position: relative; width: 712px; }",
	".framer-zU7Ek .framer-o2razv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 8px 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 712px; }",
	".framer-zU7Ek .framer-1yggvvu-container, .framer-zU7Ek .framer-wr1uck-container, .framer-zU7Ek .framer-1d7wac7-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-zU7Ek .framer-11sf07u { --framer-text-wrap-override: balance; flex: none; height: auto; max-width: 550px; position: relative; width: 100%; }",
	...css,
	'.framer-zU7Ek[data-border="true"]::after, .framer-zU7Ek [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerWUYpOtsm9 = withCSS2(Component2, css3, "framer-zU7Ek");
var stdin_default6 = FramerWUYpOtsm9;
FramerWUYpOtsm9.displayName = "Job Item";
FramerWUYpOtsm9.defaultProps = {
	height: 142.5,
	width: 712,
};
addPropertyControls2(FramerWUYpOtsm9, {
	ED1lsKYfZ: {
		defaultValue: "Full-Stack Developer",
		displayTextArea: false,
		title: "Job Title",
		type: ControlType2.String,
	},
	eYydo1Kt8: {
		defaultValue: "2022 - Now",
		displayTextArea: false,
		title: "Timeframe",
		type: ControlType2.String,
	},
	L4jz4no0O: {
		defaultValue: "Lumina Tech",
		displayTextArea: false,
		title: "Company",
		type: ControlType2.String,
	},
	vcBwwvsTj: {
		defaultValue: "Berlin",
		displayTextArea: false,
		title: "Location",
		type: ControlType2.String,
	},
	y47aed1rw: {
		defaultValue:
			"At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering. At Lumina Tech I strengthened my foundation in algorithms, data structures, and software engineering.",
		displayTextArea: true,
		title: "Job Description",
		type: ControlType2.String,
	},
	DRAi1KyCB: {
		defaultValue: true,
		title: "Current",
		type: ControlType2.Boolean,
	},
});
addFonts(
	FramerWUYpOtsm9,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HeadingFonts,
		...SmallInfoIconFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:job-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders JobItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var job_item_default = ComponentWithRoot;
export { job_item_default as default };
