// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1280626051fdb272 "MyWebAppOMK", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-TYUG5XBE.js";
import { routes } from "./chunks/chunk-4RKJF2MS.js";

// virtual:colored-tag
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/A7ClV22huCMtfSerzc5b/gm7IUBk8uDBJySS8wjoO/uKY4L9q_E.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-SPmv9";
var variantClassNames = {
	S4pCuV4rw: "framer-v-1fafaa7",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		GQUufrkr3: text ?? props.GQUufrkr3 ?? "Open to Work",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		GQUufrkr3,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "S4pCuV4rw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1fafaa7",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"S4pCuV4rw"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-d0fdb86e-048a-4262-a382-354e31e865d4, rgb(66, 52, 43))",
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							boxShadow:
								"0px 0.7065919983928324px 0.4239551990356995px -0.5px rgba(0, 0, 0, 0.24), 0px 1.8065619053231785px 1.0839371431939073px -1px rgba(0, 0, 0, 0.24), 0px 3.6217592146567767px 2.1730555287940665px -1.5px rgba(0, 0, 0, 0.23), 0px 6.8655999097303715px 4.119359945838224px -2px rgba(0, 0, 0, 0.22), 0px 13.646761411524492px 8.188056846914698px -2.5px rgba(0, 0, 0, 0.2), 0px 30px 18.000000000000004px -3px rgba(0, 0, 0, 0.16)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-wtdqw2"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"VzEPSWyIj"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-c89ea9f4-1c08-4225-bee9-c2e710a47467, rgb(208, 165, 139))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={GQUufrkr3}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1hy0j4h"}
									data-styles-preset={"uSha1VCB0"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-c89ea9f4-1c08-4225-bee9-c2e710a47467, rgb(208, 165, 139)))",
									}}
								>
									{"Open to Work"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SPmv9.framer-6yedo0, .framer-SPmv9 .framer-6yedo0 { display: block; }",
	".framer-SPmv9.framer-1fafaa7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 2px 8px 2px 8px; position: relative; width: min-content; }",
	".framer-SPmv9 .framer-wtdqw2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FrameruKY4L9q_E = withCSS(Component, css2, "framer-SPmv9");
var stdin_default = FrameruKY4L9q_E;
FrameruKY4L9q_E.displayName = "Colored Tag";
FrameruKY4L9q_E.defaultProps = {
	height: 18.5,
	width: 101.5,
};
addPropertyControls(FrameruKY4L9q_E, {
	GQUufrkr3: {
		defaultValue: "Open to Work",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FrameruKY4L9q_E,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:colored-tag
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ColoredTagFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var colored_tag_default = ComponentWithRoot;
export { colored_tag_default as default };
