// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1280626051fdb272 "MyWebAppOMK", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Note Block Education' | 'Variant 2' // Variant
 * degreeTitle?: string // Degree Title
 * time?: string // Time
 * university/Institution?: string // University/Institution
 * location?: string // Location
 * highestDegree?: boolean // Highest degree
 * text?: string // Text
}} Props

 */
import { stdin_default } from "./chunks/chunk-GKG3KNV4.js";
import "./chunks/chunk-KAGOU6RE.js";
import "./chunks/chunk-RWVAQEMV.js";
import "./chunks/chunk-XBQFWPRW.js";
import "./chunks/chunk-TYUG5XBE.js";
import "./chunks/chunk-6HGRWQMP.js";
import "./chunks/chunk-V7X3YXJE.js";
import "./chunks/chunk-EMY4GVBR.js";
import { routes } from "./chunks/chunk-4RKJF2MS.js";

// virtual:education-item
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KjeAJWzkG",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders EducationItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var education_item_default = ComponentWithRoot;
export { education_item_default as default };
