// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1280626051fdb272 "MyWebAppOMK", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Mobile' // Variant
 * link?: string // Link
 * companyLogo?: {src: string, srcSet?: string, alt?: string} // Company Logo
 * projectTitle?: string // Project Title
 * onO97a1oqC5Change?: any // onO97a1oqC5Change
 * subheading?: string // Subheading
 * onndYjGLVI5Change?: any // onndYjGLVI5Change
}} Props

 */
import { stdin_default } from "./chunks/chunk-NEHENOOT.js";
import "./chunks/chunk-FT5224EO.js";
import "./chunks/chunk-6HGRWQMP.js";
import "./chunks/chunk-V7X3YXJE.js";
import { routes } from "./chunks/chunk-4RKJF2MS.js";

// virtual:project-item
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BzeE26Upx",
	xl: "xVqzW6y79",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1280626051fdb272676e076e4a2142a6c66375c01810996d3230bbf855fdc9d8"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var project_item_default = ComponentWithRoot;
export { project_item_default as default };
